import test from 'node:test';
import assert from 'node:assert/strict';
import { CombatSimulation, distanceToSegment, type CombatHost, type CombatTarget, type WeaponProfile, type CombatHit } from '../src/combat.ts';
function arena(weapon:WeaponProfile={kind:'sword',range:2.2,arc:.2}){
  const player={x:0,z:0};let facing=0;const targets:CombatTarget[]=[];const hits:{id:string;impact:CombatHit}[]=[];
  const host:CombatHost={position:()=>player,facing:()=>facing,face:v=>facing=v,targets:()=>targets,weapon:()=>weapon,stats:()=>({attack:10,critChance:0}),move:(x,z)=>{player.x+=x;player.z+=z;},effect:()=>{},hit:(target,impact)=>{hits.push({id:target.id,impact});target.hp-=impact.amount;}};
  const simulation=new CombatSimulation(host,()=>.5);
  const enemy=(id:string,x:number,z:number)=>{const target={id,x,z,hp:10000,radius:.5};targets.push(target);return target;};
  const run=(seconds:number,active=true)=>{for(let t=0;t<seconds-.0001;t+=.025)simulation.update(Math.min(.025,seconds-t),active);};
  return {simulation,enemy,hits,run,player,host};
}
test('sword cone hits adjacent foes in front and excludes a foe behind',()=>{const a=arena(),front=a.enemy('front',0,2);a.enemy('beside',1,1.5);a.enemy('behind',0,-2);assert.equal(a.simulation.basic(front),true);assert.deepEqual(a.hits.map(h=>h.id).sort(),['beside','front']);});
test('gun projectile takes time to travel and is consumed by first enemy',()=>{const a=arena({kind:'gun',range:10,shot:'pea'}),front=a.enemy('first',0,5);a.enemy('behind',0,7);assert.equal(a.simulation.basic(front),true);assert.equal(a.hits.length,0);a.run(.1);assert.equal(a.hits.length,0);a.run(.5);assert.deepEqual(a.hits.map(h=>h.id),['first']);});
test('projectiles use swept collision instead of tunnelling through a small target',()=>{const a=arena({kind:'gun',range:10}),target=a.enemy('tiny',0,5);target.radius=.01;a.simulation.basic(target);a.simulation.update(.5);assert.equal(a.hits.length,1);});
test('projectiles stop at an obstacle before hitting enemies',()=>{const a=arena({kind:'gun',range:10}),target=a.enemy('behind',0,5);a.host.clearShot=()=>false;a.simulation.basic(target);a.run(1);assert.equal(a.hits.length,0);assert.equal(a.simulation.projectiles.length,0);});
test('spin deals repeated damage and all delayed attacks pause together',()=>{const a=arena();a.enemy('nearby',0,2);a.simulation.skill(0);a.run(1,false);assert.equal(a.hits.length,0);a.run(.1);assert.equal(a.hits.length,1);a.run(1,false);assert.equal(a.hits.length,1);a.run(2.2);assert.equal(a.hits.length,10);});
test('dash hits each enemy along its route once and does not hit distant foes',()=>{const a=arena();a.enemy('first',0,2);a.enemy('second',0,5);a.enemy('distant',7,2);a.simulation.skill(1);a.run(.3);assert.equal(a.hits.filter(h=>h.id==='first').length,1);assert.equal(a.hits.filter(h=>h.id==='second').length,1);assert.equal(a.hits.some(h=>h.id==='distant'),false);assert.ok(a.player.z>6);});
test('slam damage occurs only on landing and includes knockup',()=>{const a=arena();a.enemy('nearby',0,2);a.simulation.skill(2);a.run(.3);assert.equal(a.hits.length,0);assert.ok(a.simulation.airborne>0);a.run(.15);assert.equal(a.hits.length,1);assert.ok(a.hits[0].impact.lift>0);});
test('reset clears delayed attacks and projectiles after travel',()=>{const a=arena();a.enemy('nearby',0,2);a.simulation.skill(0);a.simulation.shoot('pea',0);a.simulation.reset();a.run(3);assert.equal(a.hits.length,0);assert.equal(a.simulation.projectiles.length,0);});
test('disguise signatures trigger distinct effects and unknown disguises are rejected',()=>{const a=arena();a.enemy('nearby',0,2);assert.equal(a.simulation.disguise('dz_superhero',0),true);assert.equal(a.simulation.statuses.flight,12);assert.equal(a.simulation.disguise('missing',0),false);a.simulation.disguise('dz_superhero',1);a.run(.3);assert.ok(a.hits.length);assert.equal(a.simulation.statuses.flight,0);});
test('segment distance clamps to finite endpoints',()=>{assert.equal(distanceToSegment({x:2,z:0},{x:0,z:0},{x:1,z:0}),1);});

test('flight leaves ranged and airborne hazards vulnerable while shield protection expires on active time',()=>{const a=arena();a.simulation.disguise('dz_superhero',0);assert.equal(a.simulation.statuses.flight,12);assert.equal(a.simulation.invulnerable,false);a.simulation.disguise('dz_knight',0);assert.equal(a.simulation.invulnerable,true);a.run(5,false);assert.equal(a.simulation.invulnerable,true);a.run(4.1);assert.equal(a.simulation.invulnerable,false);assert.ok(a.simulation.statuses.flight>0);});
test('dash protection ends after its movement completes',()=>{const a=arena();a.simulation.skill(1);assert.equal(a.simulation.invulnerable,true);a.run(.3);assert.equal(a.simulation.invulnerable,false);});
test('eye laser sweeps from left to right without reacquiring the nearest target',()=>{const a=arena();const center=a.enemy('center',0,6),left=a.enemy('left',Math.sin(-.65)*8,Math.cos(-.65)*8),right=a.enemy('right',Math.sin(.65)*8,Math.cos(.65)*8);center.radius=left.radius=right.radius=.1;a.enemy('behind',0,-6);a.simulation.disguise('dz_superhero',2);a.run(.3);assert.deepEqual(a.hits.map(h=>h.id),['left']);a.run(1);assert.deepEqual(a.hits.map(h=>h.id),['left','center','right']);assert.ok(a.hits.every(h=>h.impact.amount===10));});
test('eye laser limits repeated hits on large targets and pauses with combat',()=>{const a=arena();const target=a.enemy('large',0,5);target.radius=6;a.simulation.disguise('dz_superhero',2);a.run(2,false);assert.equal(a.hits.length,0);a.run(1.3);assert.equal(a.hits.length,5);});