import test from 'node:test';
import assert from 'node:assert/strict';
import { FishingSimulation, selectCatch } from '../src/fishing.ts';
function advance(f:FishingSimulation,seconds:number,held=false){for(let t=0;t<seconds;t+=.025)f.update(.025,held);}
function reachBite(f:FishingSimulation){for(let i=0;i<2000&&f.phase!=='bite';i++)f.update(.025,false);assert.equal(f.phase,'bite');}
test('a missed bite returns to waiting and records one bait-consuming miss',()=>{const f=new FishingSimulation({quality:0,power:.6,bait:false,random:()=>.1});assert.equal(f.phase,'cast');advance(f,.6);assert.equal(f.phase,'waiting');reachBite(f);advance(f,1);assert.equal(f.phase,'waiting');assert.equal(f.missedBites,1);assert.match(f.reason,/missed/);reachBite(f);assert.equal(f.press(),true);});
test('pressing on the bite hooks the fish while pressing early cannot hook',()=>{const f=new FishingSimulation({quality:0,power:.6,bait:false,random:()=>.1});advance(f,.6);assert.equal(f.press(),false);assert.equal(f.phase,'waiting');reachBite(f);assert.equal(f.press(),true);assert.equal(f.phase,'fight');});
test('paused fishing leaves bite timer and line tension unchanged',()=>{const f=new FishingSimulation({quality:0,power:.6,bait:false,random:()=>.1});reachBite(f);f.update(20,false,false);assert.equal(f.phase,'bite');f.press();const tension=f.tension;f.update(20,true,false);assert.equal(f.tension,tension);});
test('holding against the fish can snap the line and leaving slack loses it',()=>{const f=new FishingSimulation({quality:0,power:1.2,bait:false,random:()=>.1});reachBite(f);f.press();advance(f,10,true);assert.equal(f.phase,'escaped');assert.match(f.reason,/snapped/);const g=new FishingSimulation({quality:1,power:.5,bait:true,random:()=>.1});reachBite(g);g.press();advance(g,6,false);assert.equal(g.phase,'escaped');assert.match(g.reason,/slack/);});
test('reeling between surges and releasing high tension can land a fish',()=>{const f=new FishingSimulation({quality:1,power:.4,bait:true,random:()=>.3});reachBite(f);f.press();for(let i=0;i<5000&&!f.finished;i++)f.update(.025,f.surge<=0&&f.tension<.68);assert.equal(f.phase,'caught');assert.equal(f.progress,1);});
test('weighted catches respect pool and bounded sizes',()=>{const pool=[{id:'tiny',weight:100,min:2,max:5},{id:'rare',weight:1,min:20,max:30}];assert.equal(selectCatch(pool,()=>0).id,'tiny');const result=selectCatch(pool,()=>.999);assert.equal(result.id,'rare');assert.ok(result.size>=20&&result.size<=30);});
test('huge fish are large samples inside the ordinary size range, never oversized junk',()=>{const result=selectCatch([{id:'carp',weight:1,min:10,max:50}],()=>.99);assert.equal(result.huge,true);assert.ok(result.size<=50);assert.equal(selectCatch([{id:'boot',weight:1,min:10,max:50,junk:true}],()=>.99).huge,false);assert.equal(selectCatch([{id:'carp',weight:1,min:10,max:50}],()=>.5).huge,false);});
