// Vietnamese for the help dialog (help-topics.ts).
// Loaded only for Vietnamese players (locales/vi-pack.ts); the English text lives in the shared content module.
import { HELP_TOPICS } from '../help-topics.ts';
/** [English title, Vietnamese title, Vietnamese text]; the English text of each topic comes from HELP_TOPICS. */
const ROWS: ReadonlyArray<readonly [string, string, string]> = [
  ['Wander', 'Di chuyển', 'Nhấn mặt đất để đi; giữ để điều khiển hướng. Dấu chỉ đánh dấu mục tiêu. Bạn cũng có thể dùng phím mũi tên. Vào Cài đặt → Bố trí phím trên máy tính để bật di chuyển bằng WASD. Cài đặt cũng cho phép bật cần điều khiển.'],
  ['Be brave', 'Chiến đấu', 'Chọn một sinh vật để đuổi theo và tấn công. Tay không đánh gần, kiếm quét một vùng, còn súng bắn từ xa.'],
  ['Four skills', 'Bốn kỹ năng', 'Q xoay tròn, W lướt, E đấm đất, R dùng tuyệt kỹ của vũ khí. Bố trí WASD dùng J/K/L/; theo cùng thứ tự. Cải trang thay đổi cả bốn kỹ năng.'],
  ['Backpack and storage', 'Túi đồ và kho', 'Nhấn I để mặc trang phục, trang bị vũ khí hoặc ăn đồ hồi máu. Cất đồ quý trong rương gần nhà. Dùng phân bón ở bảng của luống cây đang lớn.'],
  ['When you fall', 'Khi bị hạ gục', 'Bạn giữ nguyên cấp độ, năng lượng và đồ đang trang bị. Quay lại túi màu hồng ở nơi ngã xuống để lấy đồ rời.'],
  ['Grow your garden', 'Trồng vườn', 'Trồng và thu hoạch để nhận EXP. Mỗi lần bón phân giảm một nửa thời gian trồng ban đầu; hai lần giúp cây chín ngay. Cây ăn quả cũng dùng được phân bón, mỗi lần giảm tối đa 2 giờ. Mở rộng từ luống đất. Nhấn một luống chín để thu cây chín trong cả vườn.'],
  ['Trade and improve', 'Mua bán và nâng cấp', 'Bán nông sản để nhận năng lượng. Mua trang bị và cần câu ở cửa hàng, nâng chỉ số nhân vật tại pha lê.'],
  ['Catch a moment', 'Thư thả câu cá', 'Giữ cần câu trong túi: cần tự xuất hiện gần mặt nước. Nhấn ao hoặc F. Nhấn Kéo hoặc phím cách khi cá cắn, giữ để kéo và thả khi dây căng. Nếu thanh lực căng đầy, dây bị kéo căng: cần tre đứt dây 60% số lần, cần vàng 30%, cần vững chãi 10%. Ao có rất nhiều cá, và cá bị câu được thay sau 3 giây. Vũ khí chiến đấu trở lại khi rời ao hoặc đánh nhau.'],
  ['Fish and forest hunting', 'Săn cá và chim rừng', 'Mua Lao săn ba chĩa tại Cửa hàng Trang bị với 1000 năng lượng rồi trang bị: lao cũng là vũ khí nặng (+100 tấn công). Chạm cá thường đang bơi trong ao hoặc nhấn Săn để phóng lao; mỗi lần phóng hồi sau 1.3 giây, cá đã săn xuất hiện lại sau 18 giây. Thỉnh thoảng Cá Thần Hồ phát sáng nổi lên ở hồ lớn trên đồng cỏ: chỉ lao săn mới bắt được, mỗi 6 giờ một lần. Trang bị cần câu từ túi đồ để câu bằng dây và bắt bóng cá bí ẩn. Sáu Diều hâu rừng lớn sống ngoài làng, trong Rừng Nấm: dùng lao hoặc vũ khí khác để đánh, nhận lông vũ và có thể nhận thịt.'],
  ['Travel among worlds', 'Du hành các hành tinh', 'Cất cánh tốn 20 năng lượng. Mỗi hành tinh yêu cầu cấp đáp xuống riêng; Hộp Đồ Chơi mở từ cấp 4. Về nhà miễn phí. Hãy khám phá đủ chín thế giới.'],
  ['Lava dangers', 'Nguy hiểm dung nham', 'Núi lửa phun khoảng 2–3 phút một lần. Rời vùng đỏ và leo đá cao. Chú ý thủy triều dung nham, lối đá nổi, thiên thạch, bão và rồng. Nguy hiểm cũng có thể làm quái bị thương.'],
  ['The ancient furnace', 'Lò rèn cổ', 'Đào tinh thể và obsidian, phá cửa hang và mang Pha Lê Lửa để soi sáng. Thắp đủ ba lò lửa để đánh thức Lò Rèn Cổ.'],
  ['Make something yours', 'Tự tay chế tạo', 'Dùng vật liệu hành tinh để chế tạo trang bị, thú cưng và đồ trang trí. Ở nhà thú cưng chờ bên chuồng vật nuôi; ngoài vùng hoang dã và trên các hành tinh khác, nó đi theo và chiến đấu cùng bạn. Đặt đồ từ túi để bạn bè ngắm khi ghé thăm.'],
  ['Five unusual planets', 'Năm hành tinh kỳ lạ', 'Hộp Đồ Chơi có quà và tàu hỏa. Rừng có gai và khí độc. Đại Dương cần dưỡng khí và có rùa để cưỡi. Mây có mây nhún và gió. Hãy thắp trụ đèn ở Bóng Đêm.'],
  ['Dress up and transform', 'Thời trang và biến hình', 'Cải trang đổi hình dáng và cả bốn kỹ năng. Thử Ninja, Pháp Sư, Hiệp Sĩ, Robot hoặc Khủng Long. Kết hợp mũ, áo và giày theo ý thích.'],
  ['Your home, a shared world', 'Nhà riêng, thế giới chung', 'Bản nhiều người chơi cho mỗi nhà thám hiểm một khu vườn riêng. Qua cổng để gặp người khác ở vùng hoang dã chung. Bản GitHub Pages là chuyến phiêu lưu một người.'],
  ['Friends and chat', 'Bạn bè và trò chuyện', 'Chọn người chơi khác để gửi lời mời kết bạn. Ghé vườn từ danh sách bạn bè. Nhấn Enter để mở trò chuyện. Tài khoản, thăm vườn và chat cần kết nối máy chủ.'],
  ['Play your way', 'Chơi theo cách của bạn', 'Chụm hai ngón hoặc cuộn để đổi độ phóng. Dùng các nút toàn màn hình và cài ứng dụng khi được hỗ trợ. Sau khi tải, phần chơi đơn có thể chạy ngoại tuyến; tính năng online vẫn cần mạng.'],
  ['Choose your path', 'Chọn đường khám phá', 'Rừng Nấm ở phía tây và Đồng Cỏ phía nam phù hợp để bắt đầu. Đầm Lầy phía bắc khó hơn. Hẻm Núi Đỏ phía đông nguy hiểm và là nơi ở của Gấu Vua.'],
  ['Animals and shelters', 'Vật nuôi và chuồng riêng', 'Mở Cửa hàng → Thú nuôi → Chuồng vật nuôi để nuôi gà, bò, vịt và heo. Chạm một con vật để thu sản phẩm của nó, hoặc chạm chuồng để thu tất cả sản phẩm đã sẵn sàng. Chuồng riêng rút ngắn thời gian sản xuất và tăng sức chứa lên năm. Hết tuổi thọ, vật nuôi thành thịt để thu. Chó canh sống lâu dài và bảo vệ vườn.'],
  ['Fruit crops', 'Cây ăn quả', 'Trồng tám loại cây ăn quả khi lên cấp. Giá hạt, cấp yêu cầu, giá thu hoạch và thời gian trồng hiển thị trước khi gieo.'],
  ['Animal pen helper', 'Rô-bốt chăm vật nuôi', 'Thuê rô-bốt tại chuồng vật nuôi với 1000 năng lượng. Rô-bốt thu sản phẩm sẵn sàng và thịt vật nuôi hết tuổi thọ, cho EXP bình thường; khi bạn về nhà, nó thu một lần lượng sản phẩm đang chờ. Có thể tạm dừng trong bảng điều khiển. Tự động cho ăn mặc định tắt; khi bật, chỉ dùng nông sản sẵn có trong túi. Rô-bốt không tự mua vật nuôi hay vật phẩm.'],
  ['Mysterious shadows', 'Bóng cá bí ẩn', 'Khi bạn đang câu, đôi khi một bóng cá có dấu hỏi nổi lên gần phao (tối đa mỗi phút một lần). Nó sẽ bơi tới cắn câu, và nếu thoát được thì quay lại tối đa ba lần thử. Kéo nó lên: 60% là cá siêu khổng lồ, còn lại là các báu vật có xác suất khác nhau.'],
  ['Weapon forging', 'Cường hóa vũ khí', 'Cường hóa vũ khí đang sở hữu đến +15. Mỗi cấp tăng 1% tấn công. Mỗi lần thử đến +5 có 50% thành công, sau đó 30%, và tiêu hao vật liệu cùng năng lượng đã ghi. Thất bại không làm giảm cấp.'],
  ['Visiting a garden', 'Ghé thăm vườn', 'Bạn có thể thử lấy cây chín ở vườn bạn bè. Chó canh sẽ chặn và cắn. Nếu không có chó, cây được lấy khỏi luống; máy chủ giới hạn mỗi khách sáu cây mỗi vườn mỗi ngày.'],
  ['Handy shortcuts', 'Phím tắt tiện dụng', 'I túi đồ · J nhật ký (P khi dùng WASD) · M bản đồ · F tương tác · Q/W/E/R kỹ năng (J/K/L/; khi dùng WASD) · Enter chat · Esc đóng. Phím tắt tạm dừng khi đang nhập chữ, kể cả tiếng Việt.'],
];
const VI_BY_TITLE = new Map(ROWS.map(([title, viTitle, viBody]) => [title, [viTitle, viBody] as const]));
export const HELP_TOPICS_VI: Record<string, string> = Object.fromEntries(HELP_TOPICS.flatMap(([, title, body]) => [[title, VI_BY_TITLE.get(title)![0]], [body, VI_BY_TITLE.get(title)![1]]]));
